### PR TITLE
Lesson 01 GitHub split

### PR DESCRIPTION
**Pull request by billmwong**

### CODE REVIEW

**Comment by billmwong** [comment]
I split up github into 3 sections, do you think that the branching and conflicts section is too big for 5 minutes?  I can try to incorporate it into the stash section, that one seems kinda small. What do you think?

**Comment by jagreene** [comment]
Eh, I think you could probably do branching as one section and conflicts/stashing as another but its not too bad the way it is. Besides that it lgtm

**Comment by yunhsincynthiachen** [comment]
I think it works the way it is. The only thing is the homework submission survey could link to the google form.

**Comment by BrennaManning** [comment]
lgtm :+1:

**Comment by dinopants174** [comment]
:ship: it

**Comment by billmwong** [comment]
Cool, added the survey link and gonna merge!

**Pull request merged**
