### PR TITLE
Updating Main ReadMe 

### PR DESCRIPTION
**Pull request by yunhsincynthiachen**
With changes to the learning objectives and course description.

### CODE REVIEW

**Comment by yunhsincynthiachen** [comment]
@billmwong pull request with small change just to get the learning objectives updated. Let me know if I'm missing any changes for the whole readme, or if I can just merge this immediately. Thanks!

**Review by billmwong — COMMENTED** [review]
Maybe put a quick link to the syllabus somewhere, with like a "check out the syllabus"

**Comment by yunhsincynthiachen** [comment]
Good call! Just put it in.

**Review by billmwong — APPROVED** [review]
Nice! Looks good :+1:

**Pull request merged**
