### PR TITLE
Initial Folder Structure

### PR DESCRIPTION
**Pull request by benkahle**
Some folder structure as we begin adding course content.

### CODE REVIEW

**Comment by EvanSimpson** [comment]
:+1:

**Comment by EvanSimpson** [comment]
Calling out @EnigMoiD @thomasnat1 if they want to review.

**Comment by jiahuang** [comment]
Oh shiiit is this coming back?

**Comment by ThomasTheDane** [comment]
Looks good to me

**Comment by paulbooth** [comment]
Yesss IT LIVES

**Pull request merged**
