### PR TITLE
Rename folders and remove flex

### PR DESCRIPTION
**Pull request by EvanSimpson**
Addresses #114 
- [x] Remove Flex Day class
- [x] Remove Class 13
- [x] Remove Class 14
- [x] Switch "class" to "lesson"
- [x] put lesson names in folder name "class02 -> class02-intro-to-javascript"
- [x] Titles within READMEs should be adjusted to new class number.

### CODE REVIEW

**Comment by EvanDorsky** [comment]
By the way, this will also be a massive rename.

**Comment by benkahle** [comment]
- Switch "class" to "lesson"
- put lesson names in folder name "class02 -> class02-intro-to-javascript"
- Titles within READMEs should be adjusted to new class number.

**Comment by EvanSimpson** [comment]
- [ ] Class 13 can be removed
- [ ] Class 14 can be removed

**Comment by benkahle** [comment]
Addressed separately

**Pull request closed without merging**
